### ISSUE TITLE
Can't fetch Product List on Strapi 4.12.5

### ISSUE THREAD

**Issue by Slazerslaze** [manishkatyan/strapi-stripe#105]
Strapi: 4.12.5
Strapi-Stripe: 3.4.1

Hey,

I'm trying to get a list of the products/subscriptions using the "/strapi-stripe/getProduct/0/10/price/asc" Endpoint. 

But it's not working. I get back an Internal Server Error with status 500.

Logs of Strapi:
error: Cannot read properties of undefined (reading 'substring')
TypeError: Cannot read properties of undefined (reading 'substring')
    at module.exports (/opt/app/node_modules/strapi-stripe/server/policies/apiToken.js:4:66)
    at policiesMiddleware (/opt/app/node_modules/@strapi/strapi/lib/services/server/policy.js:17:28)
    at dispatch (/opt/app/node_modules/koa-compose/index.js:42:32)
    at /opt/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:33:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
Is there a way to fix this?

**Comment by nishekh-e-r** [comment]
We are no longer maintaining this plugin. If you are seeking paid support, feel free to reach out to [support@asyncweb.io](mailto:support@asyncweb.io)
